project_id = "cuidado-constante"

[functions.ingest-gps]
verify_jwt = false

[functions.ingest-ble]
verify_jwt = false

[functions.get-latest-gps]
verify_jwt = false

[functions.register-collar]
verify_jwt = false

[functions.delete-account]
verify_jwt = false

[functions.request-gps-update]
verify_jwt = false

[functions.poll-gps-request]
verify_jwt = false
