project_id = "cuidado-constante"

[functions.ingest-gps]
verify_jwt = false

[functions.ingest-ble]
verify_jwt = false

[functions.get-latest-gps]
verify_jwt = false

[functions.register-collar]
verify_jwt = false
